name: Playwright Tests

on:
    push:
        branches: [main, master, develop]
    pull_request:
        branches: [main, master, develop]
jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        strategy:
            matrix:
                env: [QA, CERT]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.20.0'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Run Playwright tests (${{ matrix.env }})
              env:
                  ENVIRONMENT: ${{ matrix.env }}
                  QA: ${{ secrets.QA_SECRET }}
                  CERT: ${{ secrets.CERT_SECRET }}
              run: npx playwright test --project=chromium --reporter=html

            - name: Upload Playwright HTML report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report-${{ matrix.env }}
                  path: playwright-report/
                  retention-days: 30
